services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: datasage-sandbox
    command: echo "Sandbox image built"



  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: